# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_image import *
from .get_region import *
from .get_size import *
from .provider import *
from .server import *
from .sshkey import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_bitlaunch.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_bitlaunch.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "bitlaunch",
  "mod": "index/server",
  "fqn": "pulumi_bitlaunch",
  "classes": {
   "bitlaunch:index/server:Server": "Server"
  }
 },
 {
  "pkg": "bitlaunch",
  "mod": "index/sshkey",
  "fqn": "pulumi_bitlaunch",
  "classes": {
   "bitlaunch:index/sshkey:Sshkey": "Sshkey"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "bitlaunch",
  "token": "pulumi:providers:bitlaunch",
  "fqn": "pulumi_bitlaunch",
  "class": "Provider"
 }
]
"""
)
