# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetSizeDiskResult',
]

@pulumi.output_type
class GetSizeDiskResult(dict):
    def __init__(__self__, *,
                 count: int,
                 size: str,
                 type: str,
                 unit: str):
        """
        :param int count: The amount of disks.
        :param str size: The size of the disk(s).
        :param str type: The type of storage disk (SSD/HDD).
        :param str unit: The unit of measurement for the disk size.
        """
        pulumi.set(__self__, "count", count)
        pulumi.set(__self__, "size", size)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "unit", unit)

    @property
    @pulumi.getter
    def count(self) -> int:
        """
        The amount of disks.
        """
        return pulumi.get(self, "count")

    @property
    @pulumi.getter
    def size(self) -> str:
        """
        The size of the disk(s).
        """
        return pulumi.get(self, "size")

    @property
    @pulumi.getter
    def type(self) -> str:
        """
        The type of storage disk (SSD/HDD).
        """
        return pulumi.get(self, "type")

    @property
    @pulumi.getter
    def unit(self) -> str:
        """
        The unit of measurement for the disk size.
        """
        return pulumi.get(self, "unit")


