// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bitlaunch.Outputs
{

    [OutputType]
    public sealed class GetSizeDiskResult
    {
        /// <summary>
        /// The amount of disks.
        /// </summary>
        public readonly int Count;
        /// <summary>
        /// The size of the disk(s).
        /// </summary>
        public readonly string Size;
        /// <summary>
        /// The type of storage disk (SSD/HDD).
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The unit of measurement for the disk size.
        /// </summary>
        public readonly string Unit;

        [OutputConstructor]
        private GetSizeDiskResult(
            int count,

            string size,

            string type,

            string unit)
        {
            Count = count;
            Size = size;
            Type = type;
            Unit = unit;
        }
    }
}
