// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bitlaunch

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/webwarrior-ws/pulumi-bitlaunch/sdk/go/bitlaunch/internal"
)

var _ = internal.GetEnvOrDefault

type GetSizeDisk struct {
	// The amount of disks.
	Count int `pulumi:"count"`
	// The size of the disk(s).
	Size string `pulumi:"size"`
	// The type of storage disk (SSD/HDD).
	Type string `pulumi:"type"`
	// The unit of measurement for the disk size.
	Unit string `pulumi:"unit"`
}

// GetSizeDiskInput is an input type that accepts GetSizeDiskArgs and GetSizeDiskOutput values.
// You can construct a concrete instance of `GetSizeDiskInput` via:
//
//	GetSizeDiskArgs{...}
type GetSizeDiskInput interface {
	pulumi.Input

	ToGetSizeDiskOutput() GetSizeDiskOutput
	ToGetSizeDiskOutputWithContext(context.Context) GetSizeDiskOutput
}

type GetSizeDiskArgs struct {
	// The amount of disks.
	Count pulumi.IntInput `pulumi:"count"`
	// The size of the disk(s).
	Size pulumi.StringInput `pulumi:"size"`
	// The type of storage disk (SSD/HDD).
	Type pulumi.StringInput `pulumi:"type"`
	// The unit of measurement for the disk size.
	Unit pulumi.StringInput `pulumi:"unit"`
}

func (GetSizeDiskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSizeDisk)(nil)).Elem()
}

func (i GetSizeDiskArgs) ToGetSizeDiskOutput() GetSizeDiskOutput {
	return i.ToGetSizeDiskOutputWithContext(context.Background())
}

func (i GetSizeDiskArgs) ToGetSizeDiskOutputWithContext(ctx context.Context) GetSizeDiskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSizeDiskOutput)
}

// GetSizeDiskArrayInput is an input type that accepts GetSizeDiskArray and GetSizeDiskArrayOutput values.
// You can construct a concrete instance of `GetSizeDiskArrayInput` via:
//
//	GetSizeDiskArray{ GetSizeDiskArgs{...} }
type GetSizeDiskArrayInput interface {
	pulumi.Input

	ToGetSizeDiskArrayOutput() GetSizeDiskArrayOutput
	ToGetSizeDiskArrayOutputWithContext(context.Context) GetSizeDiskArrayOutput
}

type GetSizeDiskArray []GetSizeDiskInput

func (GetSizeDiskArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetSizeDisk)(nil)).Elem()
}

func (i GetSizeDiskArray) ToGetSizeDiskArrayOutput() GetSizeDiskArrayOutput {
	return i.ToGetSizeDiskArrayOutputWithContext(context.Background())
}

func (i GetSizeDiskArray) ToGetSizeDiskArrayOutputWithContext(ctx context.Context) GetSizeDiskArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSizeDiskArrayOutput)
}

type GetSizeDiskOutput struct{ *pulumi.OutputState }

func (GetSizeDiskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSizeDisk)(nil)).Elem()
}

func (o GetSizeDiskOutput) ToGetSizeDiskOutput() GetSizeDiskOutput {
	return o
}

func (o GetSizeDiskOutput) ToGetSizeDiskOutputWithContext(ctx context.Context) GetSizeDiskOutput {
	return o
}

// The amount of disks.
func (o GetSizeDiskOutput) Count() pulumi.IntOutput {
	return o.ApplyT(func(v GetSizeDisk) int { return v.Count }).(pulumi.IntOutput)
}

// The size of the disk(s).
func (o GetSizeDiskOutput) Size() pulumi.StringOutput {
	return o.ApplyT(func(v GetSizeDisk) string { return v.Size }).(pulumi.StringOutput)
}

// The type of storage disk (SSD/HDD).
func (o GetSizeDiskOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetSizeDisk) string { return v.Type }).(pulumi.StringOutput)
}

// The unit of measurement for the disk size.
func (o GetSizeDiskOutput) Unit() pulumi.StringOutput {
	return o.ApplyT(func(v GetSizeDisk) string { return v.Unit }).(pulumi.StringOutput)
}

type GetSizeDiskArrayOutput struct{ *pulumi.OutputState }

func (GetSizeDiskArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetSizeDisk)(nil)).Elem()
}

func (o GetSizeDiskArrayOutput) ToGetSizeDiskArrayOutput() GetSizeDiskArrayOutput {
	return o
}

func (o GetSizeDiskArrayOutput) ToGetSizeDiskArrayOutputWithContext(ctx context.Context) GetSizeDiskArrayOutput {
	return o
}

func (o GetSizeDiskArrayOutput) Index(i pulumi.IntInput) GetSizeDiskOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetSizeDisk {
		return vs[0].([]GetSizeDisk)[vs[1].(int)]
	}).(GetSizeDiskOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GetSizeDiskInput)(nil)).Elem(), GetSizeDiskArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSizeDiskArrayInput)(nil)).Elem(), GetSizeDiskArray{})
	pulumi.RegisterOutputType(GetSizeDiskOutput{})
	pulumi.RegisterOutputType(GetSizeDiskArrayOutput{})
}
