// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetSizeDisk {
    /**
     * The amount of disks.
     */
    count: number;
    /**
     * The size of the disk(s).
     */
    size: string;
    /**
     * The type of storage disk (SSD/HDD).
     */
    type: string;
    /**
     * The unit of measurement for the disk size.
     */
    unit: string;
}

